# Ultralytics YOLO 🚀, AGPL-3.0 license
# Default solutions settings

names: dict   # (dict) solutions dictionary
view_img: False   # (bool) display an output image
window_name: "Ultralytics Solutions"
line_thickness: 2
track_thickness: 2
draw_tracks: False
track_color: None

# Object counter settings -----------------------------------------------------------------
reg_pts: &reg_pts "[(20, 400), (1260, 400)]"
count_reg_color: &count_reg_color "(255, 0, 255)"
count_txt_color: "(0, 0, 0)"
count_bg_color: "(255, 255, 255)"
view_in_counts: True
view_out_counts: True
region_thickness: 5
line_dist_thresh: &line_dist_thresh 15


# Workouts monitoring settings ------------------------------------------------------------
kpts_to_check: [6, 8, 10]
pose_up_angle: 145
pose_down_angle: 90
pose_type: "pullup"

# Anchors and aliases ---------------------------------------------------------------------
spdl_dist_thresh: *line_dist_thresh     # For speed estimation
region_color: *count_reg_color    # For Queue management


# Heatmaps settings -----------------------------------------------------------------------
shape: "circle"
heatmap_alpha: 0.5
count_reg_pts: *reg_pts
decay_factor: 0.99
colormap: cv2.COLORMAP_JET

# Distance calculation settings -----------------------------------------------------------
pixels_per_meter: 10
line_color: (255, 255, 0)
centroid_color: (255, 0, 255)